In [ ]:
RUNNING_LOCALLY = True

In [1]:
import os

if not RUNNING_LOCALLY:
    os.chdir("/home/yash/")
    print("Current Directory ->", os.getcwd())

    # Ensure that you are working in the right environment
    !echo $CONDA_PREFIX

Current Directory -> /home/yash
/opt/conda


In [6]:
import gym
import time
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [3]:
env = gym.make("Riverraid-v4")

/opt/conda/lib/python3.7/site-packages/gym/envs/registration.py:506: UserWarning: WARN: The environment Riverraid-v4 is out of date. You should consider upgrading to version `v5` with the environment ID `ALE/Riverraid-v5`.
  f"The environment {path} is out of date. You should consider "
A.L.E: Arcade Learning Environment (version 0.7.5+db37282)
[Powered by Stella]


In [8]:
# Number of steps you run the agent for 
num_steps = 500

obs = env.reset()

print("Initial obs", obs)
for step in range(num_steps):
    # take random action, but you can also do something more intelligent
    # action = my_intelligent_agent_fn(obs) 
    action = env.action_space.sample()
    
    # apply the action
    obs, reward, done, info = env.step(action)
    print(f"Step {step} obs {obs} reward {reward} info {info}")
    
    # Render the env
    # env.render()

    # Wait a bit before the next frame unless you want to see a crazy fast video
    time.sleep(0.001)
    
    # If the epsiode is up, then start another one
    if done:
        env.reset()

# Close the env
env.close()

Initial obs [[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [110 156  66]
  [110 156  66]
  [110 156  66]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]
Step 0 obs [[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [170 170 170]
  [170 170 170]
  [170 170 170]]

 ...

 [[  0   0   0]
  [  0   0   